name: project_work
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  google_fonts: ^0.3.9
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  video_player:
  flutter_rating_bar: ^3.0.0
  http: ^0.12.0+4
  flutter_sound: ^2.1.1
  intl: ^0.15.6
  url_launcher: ^5.2.5
  flutter_snake_navigationbar: ^0.2.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  rflutter_alert: ^1.0.3
 #cloud_firestore: ^0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/login.jpg
     - assets/icons/ic_play.png
     - assets/icons/2.0x/ic_play.png
     - assets/icons/3.0x/ic_play.png
     - assets/icons/ic_stop.png
     - assets/icons/2.0x/ic_stop.png
     - assets/icons/3.0x/ic_stop.png
     - assets/icons/ic_pause.png
     - assets/icons/2.0x/ic_pause.png
     - assets/icons/3.0x/ic_pause.png
     - assets/icons/ic_mic.png
     - assets/icons/2.0x/ic_mic.png
     - assets/icons/3.0x/ic_mic.png
     - assets/icons/ic_volume_down.png
     - assets/icons/2.0x/ic_volume_down.png
     - assets/icons/3.0x/ic_volume_down.png
     - assets/icons/ic_volume_up.png
     - assets/icons/2.0x/ic_volume_up.png
     - assets/icons/3.0x/ic_volume_up.png
     - assets/images/alleviatelogo.jpg
     - assets/images/Artboard.png
     - assets/images/Artboardd.png
     - assets/images/happyicon.png
     - assets/images/chaticon.png
     - assets/images/contacticon.png
     - assets/images/homeicon.png
     - assets/images/diaryicon.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Pacifico
        fonts:
          - asset: assets/fonts/Pacifico.ttf
          - asset: assets/fonts/Pacifico.ttf
            style: italic

      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          - asset: assets/fonts/Raleway/Raleway-Light.ttf
            weight: 100
          - asset: assets/fonts/Raleway/Raleway-Bold.ttf
            weight: 700

      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
            weight: 100
          - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
            weight: 700

      - family: Lato
        fonts:
          - asset: assets/fonts/Lato/Lato-Regular.ttf
          - asset: assets/fonts/Lato/Lato-Light.ttf
            weight: 100
          - asset: assets/fonts/Lato/Lato-Bold.ttf
            weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
